### PR TITLE
Implement setting access rights for subtree

### PR DESCRIPTION
**Pull request by literarymachine**
Fixes EDOZWO-422

### CODE REVIEW

**Comment by jschnasse** [comment]
on test.
Works nice! Possible to add a throbber?

**Comment by jschnasse** [comment]
on test

**Comment by jschnasse** [comment]
on test

**Comment by jschnasse** [comment]
not completely sure about this. actions in the tree-navigator are still reachable. users are able to modify the structure of a complex object while a server thread is operating on the same objects. Why not open a overlay, freeze the main window and force the user to wait for an automatic close.

**Comment by literarymachine** [comment]
Ok. Will have to implement this "blocker" for all actions (saving, deleting, ...).

**Comment by jschnasse** [comment]
I made a new Ticket EDOZWO-452.

**Comment by jschnasse** [comment]
undeployed.

**Comment by jschnasse** [comment]
on test

**Pull request merged**
