### PR TITLE
EDOZWO-517

### PR DESCRIPTION
**Pull request by literarymachine**

### CODE REVIEW

**Comment by literarymachine** [comment]
Please note that the lobid-host now has to be configured to align with the namespace of the resources, i.e. no more `http://api.lobid.org` but `http://lobid.org`, `http://test.lobid.org` etc.

**Comment by jschnasse** [comment]
on test. Unsure what this does, since system works as expected before (?). Had to reset configuration under 'Storage', otherwise throws exception on import.

**Comment by literarymachine** [comment]
This is indeed a subtle change. Before, the lobid-namespace was hardcoded and independent of the "lobid-Host" setting in the storage configuration. Now the lobid-Host is also used as the namespace of lobid-resources so that we can configure e.g. against test.lobid.org. You had to update the conf to point to lobid.org (at least I had my system set up to use api.lobid.org which does not work any longer).

**Comment by jschnasse** [comment]
on test

**Pull request merged**
