### PR TITLE
EDOZWO-419

### PR DESCRIPTION
**Pull request by literarymachine**

### CODE REVIEW

**Comment by literarymachine** [comment]
For necessary theme updates see https://github.com/edoweb/edoweb-drupal-theme/pull/12

**Comment by jschnasse** [comment]
on test. seems the index mapping is not correct applied. I'm working on it.

**Comment by jschnasse** [comment]
on test

**Comment by literarymachine** [comment]
Please run update script.

**Comment by jschnasse** [comment]
on test

**Comment by jschnasse** [comment]
The following updates returned messages
edoweb module
Update #7144

    Failed: FieldException: Es wurde versucht, eine Instanz eines field_edoweb_webpage_archived-Felds anzulegen, das nicht existiert oder nicht aktiv ist. in field_create_instance() (Zeile 476 von /opt/regal/drupal-7.32/modules/field/field.crud.inc).

**Comment by jschnasse** [comment]
problems to push to production (see msg before).

**Pull request merged**
