### PR TITLE
EDOZWO-531

### PR DESCRIPTION
**Pull request by literarymachine**
Please leave PR open.

### CODE REVIEW

**Comment by jschnasse** [comment]
on test

**Comment by literarymachine** [comment]
On thing I just realized: this could well result in performance problems because I try to parse _all_ API responses as JSON to check if there is a `text` property to use. One way around this would be to have an explicit list of URIs / URI patterns that return message and code. Is this anything but `resource/{id}`?

**Comment by jschnasse** [comment]
The original idea was to provide messages only for errors, e.g. if HTTP status code is > 400.

**Comment by literarymachine** [comment]
Ok. But should we stick with this if we really want to drive UI-Feedback by API messages?

**Comment by jschnasse** [comment]
Good point. To become more concrete: The api will respond with a json message on PUT, POST, DELETE actions and also on GET if HTTP-Status is >=400. 
Special case [chunked responses](https://en.wikipedia.org/wiki/Chunked_transfer_encoding):
If the response comes with Transfer-Encoding field with a value of "chunked", the front end has to stream the response immediately to the notification area. In that case the user has to read through the notification to understand what has happened. At the moment it is unclear to me how to close a chunked response with a status code other than 200 in play2. But I will further investigate on this.


 What do you think?

**Comment by jschnasse** [comment]
Ah, setting apache to "ProxyErrorOverride Off" fixed the wrongly delivered html-page in case of 410 Gone.

**Comment by jschnasse** [comment]
Ok, an extended version with messages on PUT,POST,DELETE and error messages is deployed on test. In case of code >=400 an additional field "error" is present. The error field contains detailed information, usually a stack trace. The error field must not be presented to guest users, but should be optionaly presented to registered users.

Todo on my site: 
- translation of messages. 
Todo on yours: 
- handle chunked responses

**Comment by jschnasse** [comment]
I found a bug:
The resource edoweb:5949116 is gone and returns the proper error message when called directly. But if you try to access resource via it's parent edoweb:5949120 the error handling is not intuitive. The error shows up directly and navigation to edoweb:5949116 is not possible via tree navigator.

**Comment by literarymachine** [comment]
> If the response comes with Transfer-Encoding field with a value of "chunked", the front end has to stream the response immediately to the notification area.

As discussed before, this is not easily implemented in our current setup. While Drupal acts as a client to the regal API, it acts as a classic server for the browser. This should be postponed until we take Drupal out of the equation and build a true web app as a front end.

**Comment by literarymachine** [comment]
> The error shows up directly and navigation to edoweb:5949116 is not possible via tree navigator.

But shouldn't the resource be removed from `/all` by the API and thus not show up in the tree at all?

**Comment by literarymachine** [comment]
> Ok, an extended version with messages on PUT,POST,DELETE and error messages is deployed on test.

I guess this stands for all requests except those to the `/search/` endpoint?

**Comment by jschnasse** [comment]
correct. Only /resource and /utils are concerned.

**Comment by jschnasse** [comment]
on test. Looks good!

**Pull request merged**
