### PR TITLE
EDOZWO-520

### PR DESCRIPTION
**Pull request by literarymachine**
Please keep PR open, optional type filtering still to come.

### CODE REVIEW

**Comment by jschnasse** [comment]
on test at ellinet-dev. Issues when trying to import HT018169214. The resource is not displayed properly  
    Notice: Undefined index: generic in edoweb_rdf_types() (line 2258 of /opt/regal/drupal-7.36/sites/all/modules/regal-drupal/edoweb/edoweb.module).
    Warning: implode(): Invalid arguments passed in edoweb_basic_view() (line 1297 of /opt/regal/drupal-7.36/sites/all/modules/regal-drupal/edoweb/edoweb.module).

**Comment by jschnasse** [comment]
If deployed the import in general seems to be broken .

**Comment by literarymachine** [comment]
Against which lobid-Index are you testing this? If I try to import at http://edoweb.literarymachine.net/resource/add/monograph, I get no hits for [HT018169214](http://lobid.org/resource/HT018169214). Which is correct, because this does not map to any of our regal-types. We still depend on the type mappings, we just allow any lobid-type known us to be imported as any regal-type (e.g. bibo:Book can be imported as a regal journal).

**Comment by literarymachine** [comment]
Sorry, I was too quick there! Had my server own configured against test.lobid.org. Will have to evaluate when I'm back from ELAG!

**Comment by literarymachine** [comment]
With EDOZWO-520 checked out, I could successfully import this: http://edoweb.literarymachine.net/resource/edoweb:5948440

I believe there is a bug in my type filter. @jschnasse, could you try importing something not typed as "Resource" in the result list?

**Comment by jschnasse** [comment]
Your example (HT015309689) works for me as well

**Comment by literarymachine** [comment]
Your example, http://lobid.org/resource/HT018169214, does not match any rdf-Type known to regal-Drupal (it seems to be very generically typed). When I fixed the bug, it will no longer show up in the result list, thus it will not be importable!

**Comment by jschnasse** [comment]
Here is a resource that does not work http://lobid.org/resource/HT018660939/about .

**Comment by jschnasse** [comment]
I think there is of course a problem with the lobid mapping here. But the requirement on our side is very clear. We need a way to import arbitrary lobid resources to any regal:type.

**Comment by literarymachine** [comment]
> Here is a resource that does not work http://lobid.org/resource/HT018660939

Yes, this is expected behavior. Again, look at the RDF-types: `frbr:Manifestation`, `lv:Miscellaneous` and `dcterms:BibliographicResource`, none of which match any regal-drupal mapping. EDOZWO-520 still only allows to import known types, what changed is that you can import any known lobid-type to any regl-type. The bug is only in the result list, which currently does not limit to known regal-drupal types.

**Comment by jschnasse** [comment]
Can we introduce BibliographicResource as a known type?

**Comment by literarymachine** [comment]
> But the requirement on our side is very clear. We need a way to import arbitrary lobid resources to any regal:type.

Ok, this is a new requirement though and not what we discussed in the last telko. If this is the requirement, there is no sense in having the checkboxes at all.

**Comment by jschnasse** [comment]
The checkboxes are there to provide filtering of the result list.

**Comment by literarymachine** [comment]
> Can we introduce BibliographicResource as a known type?

Yes, we can! I'll do that later, adding basically all descriptive MD fields that we have, ok?

**Comment by literarymachine** [comment]
Both [HT018660939](http://edoweb.literarymachine.net/resource/edoweb:5948442) and [HT018169214](http://edoweb.literarymachine.net/resource/edoweb:5948441) can now be imported. During import, they are detected as a generic "Bibliographic Resource", I imported one as a journal and one as a monograph. @jschnasse could you try this out and confirm before I push?

**Comment by jschnasse** [comment]
Nice. I've tried to import HT018458921 as monograph and it works: http://edoweb.literarymachine.net/resource/edoweb:5948443
- Checkboxes for type filtering should be off by default (search in all resources as default)
- Strange,  I tried to adopt the title from parent on http://edoweb.literarymachine.net/resource/edoweb:5948444 and it did not work.

**Comment by literarymachine** [comment]
> Checkboxes for type filtering should be off by default (search in all resources as default)

ACK, have not worked on the checkbox / filtering bug yet

**Comment by literarymachine** [comment]
> Strange, I tried to adopt the title from parent on http://edoweb.literarymachine.net/resource/edoweb:5948444 and it did not work.

Strange indeed, as it is filled into the form field. Manually entering the same string works, I believe this is an unrelated bug!

**Comment by jschnasse** [comment]
on ellinet-dev

**Comment by jschnasse** [comment]
on test

**Pull request merged**
