### PR TITLE
Add 'part' bundle

### PR DESCRIPTION
**Pull request by literarymachine**
Currently, 'part' can be a child of anything but 'file' (leaf node) and
can contain anything but 'monograph' and 'journal' (root nodes).

Please run update script.

### CODE REVIEW

**Comment by literarymachine** [comment]
Also, see edoweb/edoweb-drupal-theme/pull/17

**Comment by jschnasse** [comment]
on test.

**Comment by jschnasse** [comment]
Hi Felix,
I'd suggest the following additions:
- include "Add Part" button to /resource page
- provide facet for type "part" 
- associate folder icon to part type: e.g. <span class="fa fa-folder"></span>

Best Jan

**Comment by literarymachine** [comment]
> associate folder icon to part type

Did you see https://github.com/edoweb/edoweb-drupal-theme/pull/17?

**Pull request merged**
