### PR TITLE
EDOZWO-459

### PR DESCRIPTION
**Pull request by literarymachine**
First take, deployed to http://edoweb.literarymachine.net/

TODO: configure fields to be displayed in compact view mode

### CODE REVIEW

**Comment by jschnasse** [comment]
I think we're on the right track. IMO 'Download' column should stay in, very practical to get direct access to fulltext! List is clearly to long now, so I will wait with merge until the view is configurable.

**Comment by literarymachine** [comment]
My approach was keep the Download-Link in the compact view - that way it is available only where applicable in the left-hand column. What do you think?

**Comment by jschnasse** [comment]
+1 makes sense

**Comment by literarymachine** [comment]
Deployed to http://edoweb.literarymachine.net/resource?query[0][facets][contentType][0]=journal

**Comment by jschnasse** [comment]
on test

**Pull request merged**
