### PR TITLE
EDOZWO-429

### PR DESCRIPTION
**Pull request by literarymachine**
Implement basic crawler configuration, please clear cache.

### CODE REVIEW

**Comment by literarymachine** [comment]
Deployed to http://edoweb.literarymachine.net/resource/edoweb%3A5948236/crawler

**Comment by jschnasse** [comment]
on test

**Comment by jschnasse** [comment]
on test

**Comment by jschnasse** [comment]
@literarymachine Please rebase literarymachine:EDOZWO-429 to origin master or merge origin master into literarymachine:EDOZWO-429

**Comment by jschnasse** [comment]
on test

**Pull request merged**
