### PR TITLE
Edozwo 411

### PR DESCRIPTION
**Pull request by literarymachine**

### CODE REVIEW

**Comment by literarymachine** [comment]
Please clear cache

**Comment by jschnasse** [comment]
on test

**Comment by jschnasse** [comment]
hm, title is prefixed with server name. My understanding is, that "Edoweb: " was requested.

**Comment by literarymachine** [comment]
Sorry, forgot to comment that I did not want to hard code this, so the
prefix is read from the "website name" setting in
admin/config/system/site-information.
Am 14.01.2015 09:00 schrieb "Jan Schnasse" <notifications@github.com>:

**Pull request merged**
